version: '3.8'

services:
  frontend:
    container_name: fantasy-league-fe-web
    build:
      context: .
      dockerfile: Dockerfile
    image: fantasy-league-frontend-web
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development 